In [2]:
import tensorflow as tf

#데이터 표현
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

#H(x1, x2, x3) = x1w1 + x2w2 + x3w3
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
#0.01, 0.001이 나올 수 있기 때문에 숫자가 복잡해지지 않게 하기 위해 1e-5 처리
train = optimizer.minimize(cost)

#세션
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
0 Cost:  9864.398 
Prediction:
 [64.69195  77.86493  76.75756  82.39514  60.413788]
10 Cost:  0.8948716 
Prediction:
 [152.5451  183.46367 180.80278 195.6982  140.96011]
20 Cost:  0.80127305 
Prediction:
 [152.80785 183.78525 181.11662 196.04042 141.2065 ]
30 Cost:  0.79799014 
Prediction:
 [152.8056  183.78831 181.11662 196.04085 141.2099 ]
40 Cost:  0.7947218 
Prediction:
 [152.80255 183.7904  181.11568 196.04025 141.21257]
50 Cost:  0.79148626 
Prediction:
 [152.7995  183.79247 181.11473 196.03964 141.21521]
60 Cost:  0.78825176 
Prediction:
 [152.79648 183.79457 181.11382 196.03906 141.21788]
70 Cost:  0.7850441 
Prediction:
 [152.79344 183.79662 181.11285 196.03847 141.2205 ]
80 Cost:  0.7818512 
Prediction:
 [152.79042 183.79868 181.11192 196.03786 141.22314]
90 Cost:  0.7786721 
Prediction:
 [152.7874  183.80074 181.111   196.03728 141.22577]
100 Cost:  0.77550

990 Cost:  0.5527555 
Prediction:
 [152.54684 183.96489 181.0363  195.9907  141.43495]
1000 Cost:  0.5508134 
Prediction:
 [152.54448 183.96649 181.03557 195.99025 141.437  ]
1010 Cost:  0.54887664 
Prediction:
 [152.54214 183.96811 181.03484 195.98982 141.43904]
1020 Cost:  0.5469483 
Prediction:
 [152.53978 183.96971 181.0341  195.98936 141.44107]
1030 Cost:  0.54503185 
Prediction:
 [152.53745 183.97131 181.03337 195.98892 141.4431 ]
1040 Cost:  0.543133 
Prediction:
 [152.53511 183.9729  181.03265 195.98846 141.44513]
1050 Cost:  0.5412334 
Prediction:
 [152.53278 183.97449 181.0319  195.98804 141.44713]
1060 Cost:  0.53935117 
Prediction:
 [152.53047 183.97609 181.0312  195.98761 141.44916]
1070 Cost:  0.5374776 
Prediction:
 [152.52815 183.97766 181.03047 195.98715 141.45116]
1080 Cost:  0.5356215 
Prediction:
 [152.52583 183.97923 181.02977 195.98671 141.45316]
1090 Cost:  0.53376436 
Prediction:
 [152.52353 183.9808  181.02904 195.98628 141.45514]
1100 Cost:  0.5319186 
Predict

In [3]:
#x1, x2, x3 데이터를 하나의 인스턴스로 넣어줌
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
          [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

#shape, 현재 위에서 인스턴스의 개수는 5개지만, 더 추가될 수 있으므로 none으로 할당.
#x에서는 x1, x2, x3 3개를 넣었으므로 3. 
X = tf.placeholder(tf.float32, shape=[None, 3])
#각각은 1개, 더 데이터를 추가할 수 있으므로 None.
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  93924.73 
Prediction:
 [[-120.09539 ]
 [-142.83553 ]
 [-141.8608  ]
 [-150.66603 ]
 [-111.653206]]
10 Cost:  8.096454 
Prediction:
 [[150.99828]
 [183.0094 ]
 [179.19438]
 [198.95451]
 [136.88745]]
20 Cost:  7.221545 
Prediction:
 [[151.81302]
 [183.99919]
 [180.16425]
 [200.01021]
 [137.64542]]
30 Cost:  7.206458 
Prediction:
 [[151.80998]
 [184.00604]
 [180.1656 ]
 [200.01123]
 [137.65364]]
40 Cost:  7.1914186 
Prediction:
 [[151.80449]
 [184.00993]
 [180.16408]
 [200.0091 ]
 [137.65962]]
50 Cost:  7.1764936 
Prediction:
 [[151.799  ]
 [184.01376]
 [180.16252]
 [200.00693]
 [137.66554]]
60 Cost:  7.1616044 
Prediction:
 [[151.79355]
 [184.01764]
 [180.16098]
 [200.00479]
 [137.67148]]
70 Cost:  7.146791 
Prediction:
 [[151.78812]
 [184.02148]
 [180.15945]
 [200.00264]
 [137.67738]]
80 Cost:  7.132074 
Prediction:
 [[151.78267]
 [184.0253 ]
 [180.15791]
 [200.0005 ]
 [137.68327]]
90 Cost:  7.117392 
Prediction:
 [[151.77725]
 [184.02911]
 [180.15639]
 [199.99835]
 [137.68915]

850 Cost:  6.177677 
Prediction:
 [[151.40901]
 [184.28944]
 [180.05359]
 [199.84622]
 [138.09642]]
860 Cost:  6.167332 
Prediction:
 [[151.40468]
 [184.2925 ]
 [180.05238]
 [199.84435]
 [138.10129]]
870 Cost:  6.1570225 
Prediction:
 [[151.40039]
 [184.29555]
 [180.0512 ]
 [199.84247]
 [138.10614]]
880 Cost:  6.146767 
Prediction:
 [[151.39609]
 [184.29858]
 [180.05   ]
 [199.84059]
 [138.11098]]
890 Cost:  6.136508 
Prediction:
 [[151.39182]
 [184.3016 ]
 [180.04883]
 [199.83871]
 [138.11583]]
900 Cost:  6.1263447 
Prediction:
 [[151.38757]
 [184.30467]
 [180.04767]
 [199.83688]
 [138.12067]]
910 Cost:  6.116216 
Prediction:
 [[151.38329]
 [184.30765]
 [180.04646]
 [199.835  ]
 [138.12547]]
920 Cost:  6.1061506 
Prediction:
 [[151.37907]
 [184.31067]
 [180.0453 ]
 [199.83316]
 [138.13026]]
930 Cost:  6.0960755 
Prediction:
 [[151.37483]
 [184.31366]
 [180.04414]
 [199.83128]
 [138.13506]]
940 Cost:  6.0860453 
Prediction:
 [[151.37065]
 [184.31668]
 [180.043  ]
 [199.82945]
 [138.139

1750 Cost:  5.401531 
Prediction:
 [[151.06813]
 [184.53224]
 [179.96074]
 [199.68881]
 [138.49121]]
1760 Cost:  5.3944006 
Prediction:
 [[151.06485]
 [184.53459]
 [179.95985]
 [199.68718]
 [138.49515]]
1770 Cost:  5.3873267 
Prediction:
 [[151.06157]
 [184.53696]
 [179.959  ]
 [199.68558]
 [138.49908]]
1780 Cost:  5.3802695 
Prediction:
 [[151.05829]
 [184.53929]
 [179.95811]
 [199.68394]
 [138.50299]]
1790 Cost:  5.3732667 
Prediction:
 [[151.05502]
 [184.54161]
 [179.95724]
 [199.68231]
 [138.50687]]
1800 Cost:  5.366241 
Prediction:
 [[151.05179]
 [184.54396]
 [179.95638]
 [199.68071]
 [138.51079]]
1810 Cost:  5.359281 
Prediction:
 [[151.04854]
 [184.54628]
 [179.9555 ]
 [199.67908]
 [138.51465]]
1820 Cost:  5.3523326 
Prediction:
 [[151.0453 ]
 [184.54858]
 [179.95465]
 [199.67746]
 [138.51852]]
1830 Cost:  5.3454294 
Prediction:
 [[151.0421 ]
 [184.5509 ]
 [179.9538 ]
 [199.67589]
 [138.52242]]
1840 Cost:  5.3385024 
Prediction:
 [[151.03888]
 [184.55319]
 [179.95293]
 [199.6742

In [5]:
import numpy as np
#csv 파일 가져오기
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

#데이터 슬라이싱
x_data = xy[:, 0:-1] #전체 n행을 다 가져오고(:), 처음부터 마지막 1개를 제외한 나머지 가져오기
y_data = xy[:, [-1]] #전체 데이터를 다 가져오고(:), 제일 마지막 데이터만 가져옴

#데이터를 잘 가져왔는지 확인
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#세션
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

#점수 물어보기
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 
x_data shape: (6, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]] 
y_data shape: (6, 1)
0 Cost: 20212.7 
Prediction:
 [[22.062855]
 [22.322376]
 [24.546741]
 [23.589237]
 [18.283314]
 [ 7.557437]]
10 Cost: 6.953062 
Prediction:
 [[154.57442]
 [181.65642]
 [181.50693]
 [194.52502]
 [139.82298]
 [ 97.16263]]
20 Cost: 5.9906464 
Prediction:
 [[155.46065]
 [182.74092]
 [182.56535]
 [195.67992]
 [140.65312]
 [ 97.78025]]
30 Cost: 5.9552245 
Prediction:
 [[155.45549]
 [182.75365]
 [182.56796]
 [195.68495]
 [140.66571]
 [ 97.79519]]
40 Cost: 5.920065 
Prediction:
 [[155.44434]
 [182.75911]
 [182.56343]
 [195.68224]
 [140.67274]
 [ 97.80601]]
50 Cost: 5.8851647 
Prediction:
 [[155.43318]
 [182.7645 ]
 [182.55887]
 [195.67947]
 [140.67972]
 [ 97.81675]]
60 Cost: 5.8504734 
Prediction:
 [[155.42206]
 [182.76988]
 [182.55432]
 [195.67671]
 [140.68666]
 [ 97.82746]]
70 Cost: 5.815998 


770 Cost: 3.891119 
Prediction:
 [[154.71947]
 [183.10852]
 [182.26656]
 [195.50433]
 [141.12306]
 [ 98.5057 ]]
780 Cost: 3.8695428 
Prediction:
 [[154.71068 ]
 [183.11272 ]
 [182.26294 ]
 [195.50218 ]
 [141.12845 ]
 [ 98.514175]]
790 Cost: 3.8481548 
Prediction:
 [[154.70195]
 [183.1169 ]
 [182.25937]
 [195.50008]
 [141.13383]
 [ 98.52262]]
800 Cost: 3.8268344 
Prediction:
 [[154.69324]
 [183.12112]
 [182.2558 ]
 [195.49797]
 [141.13922]
 [ 98.53105]]
810 Cost: 3.805703 
Prediction:
 [[154.68456]
 [183.12527]
 [182.25224]
 [195.49586]
 [141.14456]
 [ 98.53946]]
820 Cost: 3.7846944 
Prediction:
 [[154.6759 ]
 [183.12943]
 [182.24867]
 [195.49376]
 [141.1499 ]
 [ 98.54782]]
830 Cost: 3.763834 
Prediction:
 [[154.6673  ]
 [183.13359 ]
 [182.24516 ]
 [195.4917  ]
 [141.15523 ]
 [ 98.556175]]
840 Cost: 3.7430992 
Prediction:
 [[154.65869]
 [183.13771]
 [182.24161]
 [195.4896 ]
 [141.16049]
 [ 98.56448]]
850 Cost: 3.722515 
Prediction:
 [[154.65015 ]
 [183.14183 ]
 [182.23811 ]
 [195.48755 

1490 Cost: 2.6504948 
Prediction:
 [[154.15715]
 [183.37846]
 [182.03542]
 [195.36972]
 [141.4677 ]
 [ 99.05147]]
1500 Cost: 2.6370456 
Prediction:
 [[154.15022]
 [183.38177]
 [182.03256]
 [195.36809]
 [141.47188]
 [ 99.05819]]
1510 Cost: 2.623736 
Prediction:
 [[154.14336 ]
 [183.38507 ]
 [182.02975 ]
 [195.36646 ]
 [141.47604 ]
 [ 99.064896]]
1520 Cost: 2.6104698 
Prediction:
 [[154.1365 ]
 [183.38837]
 [182.02693]
 [195.36487]
 [141.48024]
 [ 99.07158]]
1530 Cost: 2.5973015 
Prediction:
 [[154.12968]
 [183.39165]
 [182.02411]
 [195.36325]
 [141.48439]
 [ 99.07825]]
1540 Cost: 2.5842247 
Prediction:
 [[154.12286 ]
 [183.3949  ]
 [182.0213  ]
 [195.36163 ]
 [141.48853 ]
 [ 99.084885]]
1550 Cost: 2.571218 
Prediction:
 [[154.11606]
 [183.39815]
 [182.0185 ]
 [195.36003]
 [141.49266]
 [ 99.09149]]
1560 Cost: 2.5582983 
Prediction:
 [[154.1093 ]
 [183.4014 ]
 [182.0157 ]
 [195.35844]
 [141.49677]
 [ 99.0981 ]]
1570 Cost: 2.5454686 
Prediction:
 [[154.10255 ]
 [183.40463 ]
 [182.01292 ]
 

In [13]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], 
                                                shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

#batch를 이용해 데이터를 읽어올 수 있음, 한 번에 10개씩 가져오라고 정의
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 4 fields but have 0 in record 0
	 [[{{node DecodeCSV_3}}]]


OutOfRangeError: FIFOQueue '_82_batch_6/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[node batch_6 (defined at <ipython-input-13-1f016d19220b>:11) ]]

Caused by op 'batch_6', defined at:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 499, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-1f016d19220b>", line 11, in <module>
    train_x_batch, train_y_batch =     tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 1019, in batch
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3964, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_82_batch_6/fifo_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[node batch_6 (defined at <ipython-input-13-1f016d19220b>:11) ]]


In [17]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'],shuffle=False,name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns
# Also specifies the type of the decoded result. 리더를 정의한부분. 
# xy에 csv를 디코드 하라
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
# xy에 읽어온 것을 배치를 이용해 읽어옴
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name='bias')

# Hypothesis
hypothesis = tf.matmul(X,W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
# Start populating the filename queue. coord 부분은 일반적으로 쓰는 부분..

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
# for 문 내 session안에서 batch를 가져옴
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],feed_dict={X:x_batch, Y:y_batch})
    if step % 100 == 0 :
        print(step, "Cost: ",cost_val,
             "\nPrediction:\n", hy_val)
coord.request_stop()
coord.join(threads)

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Expect 4 fields but have 0 in record 0
	 [[{{node DecodeCSV_2}}]]


OutOfRangeError: FIFOQueue '_163_batch_9/fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
	 [[node batch_9 (defined at <ipython-input-17-3c69f38b6f70>:16) ]]

Caused by op 'batch_9', defined at:
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 499, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-3c69f38b6f70>", line 16, in <module>
    train_x_batch, train_y_batch =     tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 1019, in batch
    name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 3964, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_163_batch_9/fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
	 [[node batch_9 (defined at <ipython-input-17-3c69f38b6f70>:16) ]]
